faq_data = [
    ("What is stress?", "Stress is your body’s response to pressure. It can be triggered by various situations or life events."),
    ("How can I deal with anxiety?", "You can try breathing exercises, journaling, or talk to a trusted friend or professional."),
    ("What are signs of depression?", "Signs include persistent sadness, fatigue, changes in sleep or appetite, and lack of interest."),
    ("Can mental health chatbots help?", "Yes, they provide support, coping strategies, and are available 24/7 for initial guidance."),
    ("How to calm down quickly?", "Try 4-7-8 breathing, count backwards from 100, or listen to relaxing sounds."),
    ("Is this chatbot confidential?", "Yes, your data is not stored or shared. This is a safe and private space."),
    ("What are symptoms of anxiety?", "Symptoms include restlessness, rapid heartbeat, difficulty concentrating, and excessive worry."),
    ("How do I know if I'm depressed?", "If you feel hopeless, low energy, and disinterested for 2+ weeks, it's a sign."),
    ("Why is mental health important?", "Mental health affects how we think, feel, and act — it’s vital for overall well-being."),
    ("Can stress affect sleep?", "Yes, stress often leads to difficulty sleeping or poor sleep quality."),
    ("What are common causes of anxiety?", "Anxiety can be triggered by trauma, stress, health conditions, or substance abuse."),
    ("How does depression feel?", "Depression feels like emptiness, sadness, or numbness that lingers for weeks."),
    ("What is cognitive behavioral therapy?", "CBT is a common therapy approach that helps manage problems by changing thinking patterns."),
    ("How can I practice mindfulness?", "Try focusing on your breath, observing thoughts without judgment, or guided meditation."),
    ("What to do during a panic attack?", "Try grounding exercises like naming objects around you or slow, deep breathing."),
    ("Can I prevent burnout?", "Yes. Take regular breaks, set boundaries, and maintain a healthy work-life balance."),
    ("How can I support a friend with depression?", "Listen without judging, encourage them to seek help, and be patient."),
    ("What is the difference between sadness and depression?", "Sadness is temporary, while depression is persistent and affects daily life."),
    ("What apps help with mental health?", "Apps like Calm, Headspace, and Wysa offer mindfulness, CBT, and support tools."),
    ("Why do I feel anxious for no reason?", "Sometimes anxiety is due to subconscious stress or a generalized anxiety disorder."),
    ("Can exercise help with stress?", "Yes, regular physical activity helps reduce cortisol and increase mood-boosting chemicals."),
    ("What is self-care?", "Self-care involves activities that nurture your physical, emotional, and mental health."),
    ("How do I improve sleep with anxiety?", "Establish a routine, avoid caffeine at night, and use relaxation techniques."),
    ("What are grounding techniques?", "Focus on senses — name 5 things you see, 4 you touch, 3 you hear, etc."),
    ("Can journaling reduce anxiety?", "Yes, writing thoughts can help process emotions and reduce anxious patterns."),
    ("Is overthinking a sign of anxiety?", "Yes, chronic overthinking often links to generalized anxiety or stress."),
    ("What is emotional fatigue?", "It's the feeling of being emotionally drained from prolonged stress or emotional labor."),
    ("Can food affect my mood?", "Yes, diets low in nutrients or high in sugar can impact mental health."),
    ("How to break the cycle of negative thoughts?", "Use CBT tools, challenge negative beliefs, and replace them with realistic ones."),
    ("Is it normal to cry often?", "Occasional crying is normal, but frequent crying may signal emotional distress."),
    ("How can breathing help with anxiety?", "Deep breathing slows your heart rate and activates calming nervous system responses."),
    ("How to stay mentally healthy during exams?", "Plan well, take breaks, eat properly, and practice mindfulness."),
    ("What are warning signs of burnout?", "Exhaustion, cynicism, and reduced performance are common burnout signs."),
    ("Can music help with mental health?", "Yes, listening to calming or uplifting music can regulate mood and reduce anxiety."),
    ("How do I manage social anxiety?", "Start small, practice exposure, and use breathing or calming techniques."),
    ("Can lack of sunlight cause sadness?", "Yes, low sunlight exposure can lead to Seasonal Affective Disorder (SAD)."),
    ("What is PTSD?", "Post-Traumatic Stress Disorder is a condition triggered by experiencing a traumatic event."),
    ("Why am I irritable all the time?", "Irritability can result from stress, poor sleep, or underlying mental health issues."),
    ("How does sleep affect mental health?", "Sleep regulates mood, stress, memory, and emotional processing."),
    ("What is a mental health emergency?", "Suicidal thoughts, psychosis, or extreme distress may require immediate help.")
]